In [1]:
import numpy as np
#create a ID array
arr1=np.array([1,2,3])
print(arr1)

[1 2 3]


In [5]:
# accessing elements from the array

arr1[2]

3

In [6]:
# change an element from the array

arr1[2]=5

arr1

array([1, 2, 5])

In [7]:
# create a 2D array

arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [9]:
#check the shape of the array

print("the shape is 2 rows and 3 columns:",arr2.shape)

the shape is 2 rows and 3 columns: (2, 3)


In [10]:
# Acessing elements from the array

print(arr2[0][2])
print(arr2[0,2])
print(arr2[0,-1])
print(arr2[-1,0])

3
3
3
4


In [12]:
# Array of type string

arr3=np.array(['India','China','USA','Mexico'])
print(arr3)

['India' 'China' 'USA' 'Mexico']


In [13]:
arr3[1]

'China'

In [18]:
# Array of evenly spaced values within a specified interval

arr = np.arange(0, 20, 2)
print (arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [20]:
# Array of evenly specified interval

arr=np.linspace(0, 10,20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [22]:
# Array of random values between 0 and 1 in a gibven shape

arr = np.random.rand(10)
print(arr)
print('\n')
arr = np.random.rand(3,4)
print(arr)

[0.00154471 0.14349175 0.22314296 0.75771495 0.85704557 0.44297012
 0.77876533 0.40416078 0.81109371 0.4133167 ]


[[0.83716675 0.12204868 0.14525517 0.85640619]
 [0.97264029 0.81316799 0.52483667 0.9688257 ]
 [0.58338944 0.34326551 0.719116   0.59296063]]


In [23]:
# Array of constant values in a given shape

print(np.full((4,6),10))

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


In [24]:
# create an array by repetition
# repeat rach element of an array by a specified number of times

arr = [0, 1, 2]
print(np.repeat(arr, 3))

[0 0 0 1 1 1 2 2 2]


In [25]:
# repeat an array by a specified number of times

arr =[0, 1, 2]
print(np.tile(arr, 3))

[0 1 2 0 1 2 0 1 2]


In [26]:
# create an idenity martrix

identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
arr = np.random.rand(5,5)
print(arr)

[[0.6740853  0.91553192 0.72529724 0.64637058 0.67095419]
 [0.15406722 0.76866399 0.75241427 0.150351   0.17665435]
 [0.09277931 0.71055001 0.46582599 0.58486465 0.98150842]
 [0.02774761 0.5989975  0.08970386 0.34324162 0.31421895]
 [0.05859646 0.91735527 0.03774876 0.72413252 0.96699595]]


In [29]:
# sum along the column
print(np.sum(arr, axis=0))

[1.0072759  3.91109868 2.07099011 2.44896038 3.11033187]


In [31]:
#sum along the row
print(np.sum(arr, axis=1))


[3.63223923 2.00215083 2.83552837 1.37390955 2.70482897]


In [33]:
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

0.5019462776570248
0.5989974989658557
0.3192684764178053
0.1019323600341467


In [35]:
#sort an array
arr = np.random.rand(5,5)
print(arr)

[[0.82115394 0.03283659 0.37868388 0.25876321 0.19680306]
 [0.46490339 0.23728611 0.8007836  0.7843999  0.76302639]
 [0.38824352 0.8155193  0.79468872 0.55914554 0.75744942]
 [0.51567711 0.91538978 0.74998542 0.32122758 0.3852088 ]
 [0.54128684 0.15035776 0.70729597 0.5587477  0.86707682]]


In [36]:
#sort along the row

print(np.sort(arr, axis=1))

[[0.03283659 0.19680306 0.25876321 0.37868388 0.82115394]
 [0.23728611 0.46490339 0.76302639 0.7843999  0.8007836 ]
 [0.38824352 0.55914554 0.75744942 0.79468872 0.8155193 ]
 [0.32122758 0.3852088  0.51567711 0.74998542 0.91538978]
 [0.15035776 0.54128684 0.5587477  0.70729597 0.86707682]]


In [37]:
# Append elements to an array

arr= np.array([4,5,6,7])

In [38]:
arr1 = np.append(arr, 8)
arr1

array([4, 5, 6, 7, 8])

In [39]:
arr2=np.append(arr, [9,10,11])
print(arr2)

[ 4  5  6  7  9 10 11]


In [40]:
# delete multiple elements
arr2 = np.array([4,5,6,7,9,10,11])
print(arr2)
print('\n')
arr5 = np.delete(arr2, [1,4])
print(arr5)

[ 4  5  6  7  9 10 11]


[ 4  6  7 10 11]


In [41]:
# combine and split an array

arr1=np.array([[1,2,3,4],[1,2,3,4]])
arr2=np.array([[5,6,7,8],[5,6,7,8]])

In [43]:
# combine the array items by column

cat = np.concatenate((arr1,arr2), axis=0)
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [44]:
# combine array items by row

cat = np. concatenate((arr1, arr2), axis=1)
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]
